name: Python

on: [push, pull_request]

jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dockerfile
        run: docker build -t server:latest .

      - name: Run docker image
        run: docker run -d -p 8080:8080 --rm server:latest

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests

      - name: Run client
        run:
          python client.py