name: Python

on: [push, pull_request]

jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dockerfile
        run: docker build -t server:latest .

      - name: Run docker image
        run: docker run --rm server:latest
  Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run:
          python client.py